import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  routes: [
    {
      description: 'Los Angeles Sample Optimization',
      result: {
        code: 0,
        summary: {
          cost: 6021,
          routes: 2,
          unassigned: 0,
          setup: 0,
          service: 2400,
          duration: 6021,
          waiting_time: 1858,
          priority: 200,
          delivery: [8],
          pickup: [8],
          distance: 91832,
        },
        routes: [
          {
            vehicle: 1,
            cost: 4842,
            steps: [
              {
                type: 'start',
                arrival: 1688122010,
                duration: 0,
                service: 0,
                waiting_time: 0,
                location: [34.06624918, -118.11066669],
                location_index: 8,
                load: [3],
                distance: 0,
              },
              {
                type: 'job',
                arrival: 1688122800,
                duration: 790,
                service: 300,
                waiting_time: 0,
                location: [34.04238041, -118.23817754],
                location_index: 3,
                id: 100,
                load: [4],
                distance: 15074,
                long_id: '100',
              },
              {
                type: 'pickup',
                arrival: 1688123710,
                duration: 1400,
                service: 300,
                waiting_time: 0,
                location: [34.03434239, -118.28358834],
                location_index: 2,
                id: 1,
                load: [9],
                distance: 23124,
                long_id: '1',
              },
              {
                type: 'job',
                arrival: 1688124542,
                duration: 1932,
                service: 300,
                waiting_time: 1858,
                location: [34.08431954, -118.25597762],
                location_index: 4,
                id: 38,
                load: [8],
                distance: 31436,
                long_id: '38',
              },
              {
                type: 'delivery',
                arrival: 1688127200,
                duration: 2432,
                service: 300,
                waiting_time: 0,
                location: [34.06892275, -118.29156827],
                location_index: 5,
                id: 1,
                load: [3],
                distance: 37176,
                long_id: '1',
              },
              {
                type: 'job',
                arrival: 1688128296,
                duration: 3228,
                service: 300,
                waiting_time: 0,
                location: [34.01103011, -118.19238067],
                location_index: 6,
                id: 18,
                load: [2],
                distance: 55405,
                long_id: '18',
              },
              {
                type: 'job',
                arrival: 1688129533,
                duration: 4165,
                service: 300,
                waiting_time: 0,
                location: [34.08659806, -118.17526366],
                location_index: 7,
                id: 28,
                load: [1],
                distance: 70419,
                long_id: '28',
              },
              {
                type: 'end',
                arrival: 1688130510,
                duration: 4842,
                service: 0,
                waiting_time: 0,
                location: [34.06624918, -118.11066669],
                location_index: 8,
                load: [1],
                distance: 81622,
              },
            ],
            service: 1800,
            duration: 4842,
            waiting_time: 1858,
            priority: 200,
            delivery: [8],
            pickup: [6],
            distance: 81622,
            geometry:
              'aq|nEnn{oUF??aB?uC?s@AeA?w@?OA{@m@@Y?K?W?kA?a@@I?Y?a@?M?w@?I?A?K?I?_@?Y?a@@O@M@YBK?QMkAA_@?M?c@A]?S?M?K?O?U?iB?eA?e@@M?M?U?MAK@S?O?K?kCBm@KICIIEICIAK?IBIBIDEFCFCJEl@?j@?ZAL@HDHDDFBHDLBf@BH?H?J?J?F@f@@`@Bj@@D?DR~B@nCFlNBzMDlJ?~@BlHBxE?bB?f@@tC@|A?n@?J@fA?pA?V?Z@x@@dA?l@?`@@bA@`E?`@BnL@V@pB?~@@t@?F?t@?tA?lA@rA?rB@fD?jABnD@xB?r@?b@?T@j@?x@@v@?fB@`@?jB@f@?N@lE@pA@|FBdF?vA?FAjAC~@Ez@IlAQxBIfACv@Ap@?l@@Z@L?FB\\Ff@Hf@Jf@Lf@Pf@JXFN|ChHr@~AHPJV`BvDFJLZ|ArDDFb@dADJt@jBNZHPn@xAP`@xB|Eb@dAtAdDzBdFjAfCp@~ArAbDbAzBbAdCP^n@|AVv@JVt@lCHZLb@JXJVFPHNLXLVHNHJFLHLJLHLJLf@n@X\\TVPPLLJLNNZ^j@|@j@lADJFPBFFPJXFVF\\BLBJHn@@PBL@T@`@@XBV?N@P?PAZ?b@Af@A\\Et@Cb@OtBC\\APKtAGl@GhAGp@E~@Cd@@ZAl@@R?\\@h@Dt@Fx@Ft@@NBR?BBJ?@BLFZJf@FZDTPj@Lb@JXJ\\Nd@Tn@Rj@@BVz@HRL\\d@zAj@bBDJ`B`FPf@Z|@f@vAbAxCNf@Vv@jAnDjAhD~AdEv@vBn@fBl@dBZv@Tj@Nb@DJDJPl@^jALd@Nl@Hb@Hb@BLNdAHn@Hr@F|@D`@?DBZB\\B`ABpAAn@AnBChDC|A?l@AfAC~BAvAC~AAdA?RAnAAh@?f@KpLCvAKjH@`BFhBDdAV~CFf@Fp@Jz@LtANxAH~@V|BX`BJj@Nn@VdANl@r@lCJb@XlARz@Jj@BRBLH|@Db@Dv@Bb@@j@@f@Az@At@?TANAPGt@CZAPGb@CTETG`@SdAYrAKh@Kf@Kn@ENG^Op@ERKf@If@Ib@Mj@Ox@Kf@GZGTGXMv@Mx@Gb@El@Ed@CZA`@C`@ChA?HAJ?^?JAjAA~@?f@?h@?N?n@Ab@?xB?xA@pC?~@@v@?j@?h@@^@R@V@T@ND\\DZFb@F`@FXFXBNHZDJFTHXJZJTFPFLHNFPDHDFDHBFHNLRHLPTJPNRRTLNJJBBFHTTPRNNFFFJDFHHHJHLLPBFFHJRDFHLFNFLFLDLBLFTDN@JBJ@L@jBA\\CVCr@Ex@E~@ErAATAZ?TZDRFH@RFNDTFd@LfAVJBfCh@fEz@TDd@HF@d@Bj@Bb@Bh@B^B|@Ff@BJ@J@l@FA\\Cb@ElBC\\G`CC`@Cp@ARAHGp@Gv@KzAQbCC^En@AFAPCZEj@CXA\\GrAMzBATCb@OnBIrAEd@Gn@Gf@QdAIp@CZCl@?f@Bh@?n@El@Ed@Bb@CRJ?xA?b@?LJpABb@?NKd@?l@EX?R?N?\\?F?N?P?F?^?f@@x@?p@@p@AXAb@?d@?l@?D?V?jABX?d@?j@@f@?j@Br@@vADwAEs@Ak@Cg@?k@Ae@?Y?kACW?E?m@?e@?c@?Y@q@@q@Ay@?g@A_@?G?Q?O?G?]?O?S?Y?m@De@?QKa@A{@BUAMFc@?yA?K?e@BOEq@AK?gBC]?o@?UDYAeAAm@n@SVMNUXUXq@|@}ArBaBzBORQTY\\g@n@e@c@USc@a@KKMKIKEEECCMAC?AAAGGc@a@WQ_@[MMEEMKYYSQ_@[IGUS[UUQ?CAECCOMEECKCK?I@UBIFIHKLIFCB?HAL?H?B@D@F@BBDFHJBJBJBV?H?@AVQz@EVEPGXKl@Oj@GVWz@CD{@`B_@p@S^GNMRGJiArBCDUd@CDS^EHCFGJKRWd@Ub@]n@m@bAa@r@]h@_@j@MPq@~@m@j@a@h@ONe@d@EHEDOPw@p@s@l@iAz@QRkA~@e@^[Ve@Xm@`@KJ_AbAs@r@SPKLGFQXIVELGRIXAB?D?F?H?B@F@L?RBJ@PDLHXJTJNHHb@`@RN|@p@HFp@t@`BdBl@l@BBzAjAlAbBr@|@`@h@LNl@r@bAjAHHHHFFPPHH|@~@JLx@|@b@d@PPVXDDNNf@h@\\^ZZVVj@h@LLVTZZHFb@b@RPHFh@d@r@l@BDt@l@JHTPFFPLTPdF|DTRf@d@z@x@b@f@d@j@j@t@Zh@X`@`AbBp@tATf@^r@Rb@R`@LVXh@f@`Ah@dAHLDFLPNf@x@|APRNTl@hAZl@JTz@`BLT~@hBr@rANXb@x@FNNXbAzBdBhDXd@PZT`@JNFLHPFHN\\xArCNVd@v@b@n@HLXn@\\t@HNHNLPRT`@d@TTPRPRNNl@j@VT`@`@b@\\ZVZRVRt@`@HFbAh@r@^VN\\NZJVFl@NTJb@HlBPP?b@DJ@J@H@L@F@J@H@F@PBH@H@J@F@D?D@D@B@B?B@B@FBF@FDHBHFXT`@`@LPFLXl@FZLb@D|@BV@P@R?P@pA@z@?d@@fABv@@v@?f@AVANETMd@GPIRY|@uAvDa@jAtBnA^Rv@f@x@f@VJRJDDPHd@XJDh@VPJXNPJtAv@d@VxCdB\\P^Rb@V|@^\\cAzBhARJGRELKNCBCBI?GCKESGCAYOOIk@]_@fACFERCFAF[?M?k@?a@Ak@?[?a@@O?a@?a@i@MMKMACEGGKGQEQE_@ESMaAAEQcAIo@Kq@UaBYiAKmACWAIKeBG}@Ek@AYEm@?GAWAUG{AAy@OmIKy@Ei@EgAMwFCo@Ac@Aa@?MCc@As@Cc@CYEWIYAEGQEICGQWOQQOOISKUGUEWCW?UBWDYHYNWVIBIHSPSPUPMHk@b@WRYPWNSHYDO@Q?SCWCk@OcBi@e@M_@Mg@Ie@U[Oc@Wc@WWS[UUOSS[Wc@_@][QSQQ[_@gAyAQUQYk@{@_@m@S]Wc@}@aBYi@]m@AEQ[Ue@S]KSGMWg@Wg@_@u@Q_@_@s@[k@EIGQa@u@S]oFgKIUS_@[o@uAmC[m@GMwBgEUg@]o@ACOWSa@i@aAMWi@cA_@m@o@_AUYY]QSW[QQQSaAaAWU_@Y{DwCUSc@]KGWSKIOQQS_@W_Ay@QQWWq@k@KKu@s@e@c@SQqAsAq@q@MMUUMO[]aAy@e@g@QSa@a@QQSS]_@}B{Cy@eA}@iBS_@KQSYe@q@q@cAoBgCSYaAwAUUWQMIQGYKGAEAGAWCOCI?M?E?]Eo@EWBSBODC@QJMHC@QPOTILILwA`Da@|@yAjCYf@e@fAQX]d@_@d@a@l@_@j@QZ]j@MROVU^_@h@S^QXOXOVOVEJEFO\\Q^Qb@KTOZKVUn@Qh@Up@Sp@W|@YhAAFoA|EUz@WPUt@]fAKRKPKJKJGBMFWJIBYDCHCFk@fBENCFMZOd@o@hBCJCJAHAFAFAJe@@S@I?}@BO?I?S@[Bo@DUBWBUDmC^WBQ?Y?mAGsCIcAEyBGm@EUCQEMCSGs@U[K[MSGQIe@OICy@[qAe@YMa@Oa@MYEKGIOYMIEMOGGMISKQIOIWKsAo@YSQIKIIIW[GGSUMOMKCEGGMIKIIEEACCKCKAIAKA}@GKAIAGCKEECGKCECC}Aw@KEKCIAGAICm@[QAAAA?A?KGcCsAsFsCPi@Ro@?G?CACACECWOVNDB@B@B?B?FSn@Qh@rFrCbCrAM^Sh@GLo@nBi@dB[`AIRCFGFGFOVKP~@BR?PHJDXLtAt@JFJA^RnAn@hDdBbAf@z@d@^RZNLFpAr@|@f@\\N|@b@~@j@HFl@\\^RfAd@v@^LFv@`@h@Xh@X`@T`@R`Af@t@^LH^RRJRJd@VLFLHh@Vd@XTHVLl@ZNHJFPJRJRJTLTLRJhAl@t@\\j@XM`@Qn@W|AYlBO|@ATYdAGn@Kl@w@fCUr@EL_@`Ae@jAMVMZ_@|@Wl@Up@KZWp@GXOh@Sr@Oj@K\\I^K`@IXGZK`@EVKj@Kf@SdAGTShAc@xB{@hEKh@UlAg@fCCJGZWrACN[dBIb@W|Ak@fEOhA_@`CG`@c@|CALEP_@hCIn@EVIl@UjBGh@QxAGh@Iv@KdAMhAOnACRKn@QbAUhAQz@q@`BKVCDc@bAw@bBQZOVQVML]Za@`@WXKNCBAHAFAF?H?Zp@?P?tCAP@FAdA@P?T?Z?P?XAbB?l@@f@Ar@@Z?T?rAAp@?f@?|@AR?T?t@?X?N?z@Az@?lA?~@?P?N?jB?`A?vB?X?nA?lCAV?D?h@@d@?hB?N?XAn@?R?p@?X?Y?q@?S?o@?Y@O?iB?e@?i@AE?W?mC@oA?Y?wB?aA?kB?O?Q?_A?mA?{@?{@@O?Y?u@?U?S?}@@g@?q@?sA@U?[?s@Ag@@AyB?UAe@A]AQAQAOAGCMAIEOI[Oi@K]CKCOCMAQAM?M?EAK@]?g@@O?u@@cBDwDBg@?CBo@IiANiBBYJcALaARuA\\cCPiATcBPoA@KJo@Fa@LaAf@mDVgBLs@Js@FSRsABKN{@TeAHe@RaAJc@VuABOz@mENs@P}@P_ARgANq@Nw@Ji@Jg@Ps@Nm@No@Nk@Rw@\\gATq@HUVu@|@{B|@wBb@kAPi@`@kARs@Vs@Pq@La@DOv@iCn@mBl@gB~DoLL_@L[Z}@Xu@`@oAj@wBBS`@}A\\sAZqANm@Pq@H]HY@G`@aBbAaEZoAXiALi@T}@Ru@R{@Nk@@ERw@Ty@Nm@Pm@Ng@Tk@Ri@To@Vm@Zs@Xm@DIFMJMzAmCr@gA`@s@Zk@|@uAFKT]l@aAzA_CtAqBNWNS\\e@RUv@y@^]TSb@_@`@]f@c@TQDEFGFCLMLKFEZWfA{@jA_A~AqADGBCFGFELKNKb@[\\[ROJKLOPOV]TURUp@s@RYZe@R[LSj@m@v@mAXc@Va@NS~AgCb@u@r@oANWVe@NYHQFIFOTa@NYP[R_@R_@LSLWFMDGDIDGDIxAoCTa@FMZm@BE^s@HOXg@HOtByDBGHOVk@HQHSJUNc@J_@BKZiCBWDe@@Q?Q@u@Bu@AeA?c@Ai@@i@?[BmAHiD@SBk@HyB@W@U@UDm@Do@BW@MD]JqAL{AJqABYBYDo@BS@U@OFm@Bm@@I?I@K@QD_@@IBY@KToBH{@Hw@H_AD_@LaBPu@BMBIHm@DSH]Ni@Ng@Ri@Vk@BGR]Xc@Za@\\_@^]ZWLIJGLILIJGNGLGd@Qh@U|@_@p@WJELGPGFCb@Q^ORIbBo@~@Y|@W`AUHCNCJAREDA~@O`AM`AIB?x@GTAJAb@ApBCp@AL?N?h@?`@?fACfA?t@A^@h@@`@@ZBP@T@\\BZD\\BZDZDbANr@Ll@HvAXl@DZ@pA?t@Af@CRArAID?n@CZAL?n@@v@Bb@DhAJ`@DVBv@Dn@@n@?j@EPAHAp@EPCl@Gd@KDAh@QLE^K`@OBALGJGb@Ud@WNIDCNIHG@?jA_A\\YVUZ[BCRQ\\]TUDGZ]d@i@Za@^g@X_@RYV_@Zg@Xe@Zg@FO`@s@Rc@b@}@Xo@Vo@r@mBNa@L_@d@wA\\cAPc@V{@BEZ{@f@}AHUFQFQHQPi@To@DITq@Rm@L]\\cAX}@Vs@Xw@J[Rk@t@uB^eA^eAz@gC`@qA^gAv@mCH[DQJ_@H_@Le@n@eCVkAT}@DKXeAZ_A\\_ARq@v@aCDMDMJ[Pi@Nc@Pi@Ne@Ro@HQHWPg@Le@^gANc@Ne@HUXy@J]La@FQNe@Pg@Ne@Pg@Na@Ts@FQBIFQRo@L]Ts@Pg@L_@L_@Vy@Pg@d@}A\\gAL_@HUL_@HUNg@FUJ_@HYRaADWDQHi@Hg@F[NoAJ_ABYJsA@]FqABq@?iB?qA?kB?y@?mA?}D?Q?O?M?_@@iC?eBAiAAmGAyD?S?s@AoA@s@?C?G@e@@]@_@Be@Ba@Da@B_@De@DYDa@DYHk@Jo@Fc@Jc@BOBKLi@Pq@HYPm@V}@\\cAHUZq@HQBGN_@b@}@l@oATc@Xo@BCh@mA\\{@Zs@LYPc@FKZy@j@{@NWFKJOLSv@uADG\\k@PWLUR[HOLMJOLOJKNOFGROJILGPKJGRIJENETGNEVGNCJARCNAhBWpFGJ?f@?\\?lAA`B?N?L?l@AT?lA?X?Z?V?l@?T?p@A^?nA@bA@hB@rAHhAF`@Pj@NXDr@JB@NDLDNJJLHLHNBLDRBb@DXDRDNFJDFBBLHRLRHZN\\HIZQt@Mj@EPEPK`@Sz@Qp@Qv@Sx@YhAMl@mBxH]|A[rAWbASz@Op@s@vCo@nCy@hDSz@GVGVOn@[pAc@jBk@|BOl@Qz@a@`B[nAUbA_@|AQr@uB|IU~@Kb@m@hCg@tBQr@GXKd@m@hCl@iCJe@FYPs@f@uBl@iCJc@T_AtB}IPs@^}ATcAZoA`@aBP{@Nm@j@}Bb@kBZqANo@FWFWR{@x@iDn@oCr@wCNq@R{@VcAZsA\\}AlByHLm@XiARy@Pw@Pq@R{@Ja@DQDQLk@Pu@H[FWJi@H]Le@No@Lm@DOBQDUFUPu@Ja@Pu@DSe@SMGiAc@OEMAM?OBMDKHIHINO\\O^KPCDGDMHODQBM@i@?aBFcAGo@Eg@Au@EMAu@?_AAs@?mBAkB@aA@WAkA@M?u@?[?i@?sA?c@?oFCQAwDCeA?o@AY?m@@SBYBYDq@JUBMBSFUJMF_@NUHu@VUFGBQFu@Rw@Rq@Lk@HiBJS@U@M?K@U?S?_@@mABo@@{@Ay@Cy@Ey@Gy@My@O_ASoFgAq@MYGQCa@Kc@E]G}@ISCQAi@EMAs@Cm@Aw@Ae@?uA?mA@c@?W?WA[?k@CG?G?g@Ea@Eg@I[EAAEA]IUEa@MaA[c@Oe@Ow@WICsBs@k@[c@I]KWKy@YUKeA]m@Ua@Qk@Qm@OYGa@ISCEAYEMAIASCIAa@CiAEiAAcA@qB@S?S?O?I?I?I?EAA?U@e@?aC@U?Q?oA?e@@u@?]?U?O?w@?}@@u@?sA?g@?eA?{A@[@K?c@?_F@qD?wA@[Ay@AMASAm@GWCQCKCq@Kq@QMCa@Mq@Wg@UCAm@Ym@_@m@a@EEsB_B[WEEc@]e@a@{@u@uBaBeBsAcA}@eDmCaAw@o@i@q@g@KG_@UKI_@Sm@Yo@Wo@Uq@SICg@Ms@Ks@Ik@Gi@Eq@AcA@{@@q@Dk@FkCl@_@HgAXeA\\a@N_@JqC|@[HMD]HMDQBa@Fq@HaADs@?g@As@E}@KSAmCW{@IKAOC_@EWEM?SCI?mAK_@COA[EO?MAUCE?GAIAG?}@IOAq@Gc@EQCa@EQCOCOCUCa@GWE[ESGSCSGWG]Gq@S}@YWKu@USGYKWKOIWKSIYKOIGC]M_@QyAo@GCoBy@o@YKEe@Qm@Ye@QIEYM[MSKIE_@OEAm@Ym@Wm@WoBw@SGOEOEYIKCk@Mk@KYGUCk@Eq@EkBIwAEa@COAC?Q?[AE?a@@G?_ABu@@C?G@WDR`AL`@FRDNLVLVXj@LTPXj@dAv@xANZHZHVDT@HBR@T@RAX?B?PCVCNKd@Oj@IZUx@WdAOf@I\\Ol@G^Eb@El@?BAd@AFA|@BhA?H@\\@LBXBTLj@Nd@L`@FN~@bCx@xBFLLZ`@bAPVPT?@PR\\`@DFjAzA|ArBl@v@j@r@nBhCzAnBbApAv@`ATXn@v@Z^LLBBB@\\\\HDZVNHHFZVZPPJt@h@l@^VN^Rv@j@LL\\`@PPHLFJFLFLBHPv@Dl@DZHv@?HHp@Fj@DLBLBJDLDRHTHTHTDJHRBDHHb@f@HFFDFFJDPLQFMDI@[@S@I@{@?W?aEFmBDiBDsABW?E?c@@k@@S@yDJcA@U?uCIqBI}@E_AEO?sAG[AcAEqAEo@Cu@?W?G?EA[AKAKAEAWKsBiAOIQKMIcAm@MGIEQMIGKKMKCCQOKMU]OWKSKOGKGIKIIGOKCAGEKGECEAIAAAE?IAOA]A}B?sA?wB?{BBo@?m@?U?M?MAkA?_@?mA?I?_A?oA@k@?g@?cC@K?uDA@IAKEOIWe@wA_@oAK[CE]kAM]K[s@{B_@PUy@Ma@ZSNb@Vx@r@zBJZL\\\\jABDJZ^nAd@vAHVDN@JAHtD@J?bCAf@?j@?nAA~@?H?lA?^?jA?L@L?T?l@?n@?zBCvB?rA?|B?\\@N@H@D?@@H@D@DBJFFDB@NJHFJHFHFJJNJRNVT\\JLPNBBLJJJHFPLHDLFbAl@LHPJNHrBhAVJD@J@J@Z@D@F?V?t@?n@BpADbADZ@rAFN?~@D|@DpBHtCHT?bAAxDKRAj@Ab@AD?V?rAChBElBE`EGV?z@?HARAZAHALEPGQMKEGGGEIGc@g@IICEISEKIUIUIUESEMCKCMEMGk@Iq@?IIw@E[Em@DGBGBEBCFEDCFCB?HAD?NBTPLLf@^j@b@t@h@`@ZfBnAPLPLHDLFLDLBLBRDV@B?N@b@@r@@`@?pB@f@?N?L?N?N@^CHAHCRIPKFENKJILKHMNODGXk@FUHi@@Q?O?Q?a@?c@?E?M?QAU?yA?K?qAAQ?_A?g@?[?}@?aA?m@?W?WBQBQDQHWNOLKHGNIJGHEXSPI^ULGL@BACICIEKCIIWCIw@}BQe@GUI]Ss@Oy@GWEYACAIKw@EYC]Gu@Ew@Cu@Ae@Aa@AQAWAYCc@B]b@}G@YHiAHgABg@@g@@s@?i@?U?G?WA[AQ?KC]C[Gm@Ec@EYG[Ia@U}@Qo@Oa@EOSk@Yq@a@aAm@mAMS[i@Ua@U_@m@}@}@uAm@gAc@aA[m@m@sAaA}BcAcCy@kBcB}DKUu@_BEKk@uAgBaEc@cA}@uB}AqDWm@]w@Wm@Q_@Se@]y@IQKUQc@c@eAg@iACIQ_@g@iAi@oAcB}Dy@oBUi@EGIQYs@KWM]Qk@Om@Ka@Kg@EQAGIe@G_@E[Gm@AUCQASAUA[Cc@A}@?kAAiDCiC?eCCaF?{@AyAAcD?W?I@]AmAAoEAuAAk@AcB?y@?i@?iAAw@?W?s@AsDAcA?e@?OAy@AwIA}CCcE?]CwH?gACsI?e@CaB?_A?sAA}B?I?MAuBAm@?wA?yB?SCaC?i@?i@CcH?{@AkA?qA?]Aa@?e@AsBAmB?sA?_AA{AAsA?kBAiA?u@AcB?cAC{H?_@?U?UHu@H_A@_A@E?KD[BKDGFGHEJCP?b@?`AARAFAJEHGHKL[HMFIJEPGJ@N?L?z@@t@?h@?PIJ?XCLANA`@AX?^?H?J?@?H?v@?L?`@?X?H?`@AjA?V?J?X?l@A@z@?N?v@@dA?r@?tC?`BG?',
            long_vehicle_id: '1',
          },
          {
            vehicle: 2,
            cost: 1179,
            steps: [
              {
                type: 'start',
                arrival: 1688111563,
                duration: 0,
                service: 0,
                waiting_time: 0,
                location: [34.0522137, -118.28427087],
                location_index: 9,
                load: [0],
                distance: 0,
              },
              {
                type: 'job',
                arrival: 1688112000,
                duration: 437,
                service: 300,
                waiting_time: 0,
                location: [34.06675919, -118.30620984],
                location_index: 0,
                id: 8,
                load: [1],
                distance: 3682,
                long_id: '8',
              },
              {
                type: 'job',
                arrival: 1688112878,
                duration: 1015,
                service: 300,
                waiting_time: 0,
                location: [34.0426885, -118.28191077],
                location_index: 1,
                id: 9,
                load: [2],
                distance: 9033,
                long_id: '9',
              },
              {
                type: 'end',
                arrival: 1688113342,
                duration: 1179,
                service: 0,
                waiting_time: 0,
                location: [34.0522137, -118.28427087],
                location_index: 9,
                load: [2],
                distance: 10210,
              },
            ],
            service: 600,
            duration: 1179,
            waiting_time: 0,
            priority: 0,
            delivery: [0],
            pickup: [2],
            distance: 10210,
            geometry:
              'kyynEfk}pUW?M?I?_A@a@?W?gA?eA@mDB[?S?I?Q?K?W?[@q@?u@@OAU?y@?YAeA?k@Ce@?}A?At@?N?^?RAp@?X?`A?P?v@?\\@h@?lA?h@?l@?T?d@@\\?RAZ@d@?F?f@?P?`@?b@?p@?b@@fA?Z?^?rA?p@AZ?F?PAjA?t@Ax@Ax@?N?B@p@AxB?z@?jB@pA?j@?~@?T?b@@tA?`B?`@?X?fA?f@?~@?pB?vA?fA@v@?tA?xA?h@?lD@l@?r@?vA?h@?b@@rA?dC?Z@|DA`E?f@@xFiAAm@?w@?S?mEBeI@k@?IAG?EAE?CASAI?m@?oCDI?e@?c@?{@AcA@k@?sA@eDA{G@zGAdD@rAAj@?bAAz@@b@?d@?H?nCEl@?H?R@?fA@pB?~@?z@?j@?d@?d@@bAJ?j@@V?d@?b@?p@AvA?X?rA?fA?dD@B?T?R?j@?b@?`@?P?jB?`D?ZAr@?r@?lAAjA?^@j@?R?VApB?R?tA?\\?l@AT?hA@b@?\\?h@?tDArD?dBAjA?lA@bB?xAAX?\\?h@?d@?R?Z?xA?p@AhC?hDAL?H?f@?j@?H?L?z@??uA?]?yCAcCA{A?uA?eDAaE?a@?mA?mA?uB?o@AqB?a@Ac@?EAUAWC]AO?OCe@C[G{@Gy@IeACc@Gw@Ca@MaBIiAC[KmBImB?AA_@Ao@A[CmB?]AoA?}@?sCA_D?]?eA?eB?Y?i@?c@?[?y@?q@?WAM?k@?cB?oD?cA?aA?a@?c@AsAA_G?W?C?O@M?M@S?M?K@I@K@GBSTaBD_@^cCD]BSLy@BONk@HWJ]HU^cAPi@Z{@HWp@iBL@B@@@AACAMAq@hBIV[z@Qh@_@bAITK\\IVOj@CNm@@_B@S?g@@e@?i@BW@}@BoA@M?u@?u@?]@S?G?C?YCMA]Ac@Ei@CM?i@AiFBm@?wA?e@@O?sC@qA@W?O?W?]?OA[@S?e@@E?',
            long_vehicle_id: '2',
          },
        ],
      },
      status: 'Ok',
      message: '',
    },
  ],
};
const routesSlice = createSlice({
  name: 'routes',
  initialState,
  reducers: {
    setRoutes(state, action) {
      return {
        ...state,
        routes: action.payload,
      };
    },
    addRoute(state, action) {
      console.log('addRoute', state, action);
      return {
        ...state,
        routes: [...state.routes, action.payload],
      };
    },
  },
});

export const routesActions = routesSlice.actions;

export default routesSlice.reducer;
